export const SET_ACTIVE_CAMERA = 'set_active_camera'
export const SET_CAMERA_ZOOM = 'set_camera_zoom'
export const SET_CAMERAROLL_PHOTOS = 'set_cameraroll_photos'
export const SET_FACES_DETECTED = 'set_faces_detected'
export const SET_PERMISSIONS_CAMERA = 'set_permissions_camera'
export const SET_PERMISSIONS_LOCATION = 'set_permissions_location'
export const SET_PHOTO = 'set_photo'
